sudo: false
language: python
python:
- '3.7'
- '3.8'
notifications:
  email: false
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=ionize setup.py test
  
after_success: coveralls
deploy:
  provider: pypi
  user: lewis.a.marshall
  password:
    secure: ED3TmnEto2g+XHZXe4HdxqQEuyn5V/erpTjbH5tkwOA2UB/eSe3mcd9nBDWg0VLeCqYAbEkIA5N+NCgKYP4n7vMYNNzU/pZ+q63cJt8DNqd2Ocxo1G7g0LEsRnuDTEad2cMKHc7eWtidJUer1j6LxzASqsK5doOudhgY1SxEX1Q=
  on:
    tags: true
    branch: master
