package:
  name: ionize
  version: "0.11.0"

source:
  git_rev: v0.11.0
  git_url: https://github.com/lewisamarshall/ionize.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy

build:
  script: python setup.py install

test:
  imports:
    - ionize

about:
  home: https://github.com/lewisamarshall/emigrate
